# name: "designite-util"

# inputs:
#   # Path to the DesigniteJava.jar file
#   designite-jar-path:
#     description: "Path to the DesigniteJava.jar file"
#     required: true
#     default: "./.github/DesigniteJava.jar"
#   # Path to the directory to be analyzed
#   input-dir-path:
#     description: "Path to the directory to be analyzed"
#     required: true
#     default: "./"
#   # Path to the output directory
#   output-dir-path:
#     description: "Path to the output directory"
#     required: true
#     default: "/tmp/Desingnite_Output_${{ github.sha }}"
#   # DesigniteJava command line arguments
#   designite-args:
#     description: "DesigniteJava command line arguments"
#     required: false
#     default: "-d"
#   # GitHub context
#   github-context:
#     description: "GitHub context"
#     required: false
#     default: ${{ toJson(github) }}

name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  designite-output-old:
    description: 'Designite Output Name Old'
    required: true
  designite-output-new:
    description: 'Designite Output Name New'
    required: true    
  repo-name:
    description: 'Repository Name'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --token=${{ inputs.github-token }}
    - --designite-output-old=${{ inputs.designite-output-old }}
    - --designite-output-new=${{ inputs.designite-output-new }}
    - --repo-name=${{ inputs.repo-name }}